from tkinter import *
root=Tk()
root.geometry("800x600")
form=Label(root,text="Student Form",font="comisence 12 bold")
form.grid(row=0,column=3,pady=10)
name=Label(root,text="Name",font="arial 12")
roll=Label(root,text="University Roll No",font="arial 12")
reg=Label(root,text="Registration No",font="arial 12")
year=Label(root,text="Year",font="arial 12")
gend=Label(root,text="Gender",font="arial 12")
dep=Label(root,text="Department",font="arial 12")
sem=Label(root,text="Semester",font="arial 12")

name.grid(row=1,column=2,padx=20)
roll.grid(row=2,column=2,padx=20)
reg.grid(row=3,column=2,padx=20)
gend.grid(row=4,column=2,padx=20)
dep.grid(row=5,column=2,padx=20)
year.grid(row=6,column=2,padx=20)
sem.grid(row=7,column=2,padx=20)

sname=StringVar()
sroll=StringVar()
sreg=StringVar()
syear=StringVar()
mgender=IntVar()
fgender=IntVar()
ogender=IntVar()
trade1=IntVar()
trade2=IntVar()
trade3=IntVar()
trade4=IntVar()
trade5=IntVar()
semester1=IntVar()
semester2=IntVar()
semester3=IntVar()
semester4=IntVar()
semester5=IntVar()
semester6=IntVar()
semester7=IntVar()
semester8=IntVar()

ename=Entry(root,textvariable=sname)
eroll=Entry(root,textvariable=sroll)
ereg=Entry(root,textvariable=sreg)
eyear=Entry(root,textvariable=syear)

ename.grid(row=1,column=3)
eroll.grid(row=2,column=3)
ereg.grid(row=3,column=3)
eyear.grid(row=6,column=3)

male=Checkbutton(root,text="Male",variable=mgender)
female=Checkbutton(root,text="Female",variable=fgender)
others=Checkbutton(root,text="others",variable=ogender)
ece=Checkbutton(root,text="ECE",variable=trade1)
cse=Checkbutton(root,text="CSE",variable=trade2)
elec=Checkbutton(root,text="ELECTRICAL",variable=trade3)
mech=Checkbutton(root,text="MECHANICAL",variable=trade4)
civ=Checkbutton(root,text="CIVIL",variable=trade5)
s1=Checkbutton(root,text="SEM 1",variable=semester1)
s2=Checkbutton(root,text="SEM 2",variable=semester2)
s3=Checkbutton(root,text="SEM 3",variable=semester3)
s4=Checkbutton(root,text="SEM 4",variable=semester4)
s5=Checkbutton(root,text="SEM 5",variable=semester5)
s6=Checkbutton(root,text="SEM 6",variable=semester6)
s7=Checkbutton(root,text="SEM 7",variable=semester7)
s8=Checkbutton(root,text="SEM 8",variable=semester8)

male.grid(row=4,column=3)
female.grid(row=4,column=4)
others.grid(row=4,column=5)
ece.grid(row=5,column=3)
cse.grid(row=5,column=4)
elec.grid(row=5,column=5)
mech.grid(row=5,column=6)
civ.grid(row=5,column=7)
s1.grid(row=7,column=3)
s2.grid(row=7,column=4)
s3.grid(row=8,column=3)
s4.grid(row=8,column=4)
s5.grid(row=9,column=3)
s6.grid(row=9,column=4)
s7.grid(row=10,column=3)
s8.grid(row=10,column=4)

root.mainloop()